[core]
allow_custom_extensions = false
report_interval = 1           # In Hours (Up to 720 (30d))
send_empty_report = true      # Start events even if all fields are (empty: true)
once_ctx_deadline = 3300      # Kill extension process with "mode: "ONCE"" after this amount of seconds. Must NOT be more than (report_interval * 3600)
disable_ip_comparsion = false # Whether to disable scanning banned IP diffs
disable_community = true      # Whether to disable downloading of []community_domain_sources
    [core.data]
    data_dir = "./data" # Directory with necessary service files
    method = "http"     # If "http" then core checks for Last-Modified tag to check if file was updated and downloading files only if remote server has newer file.
                        # If "hash" then core downloading all files every scan. Hash compare of merged files performed in both "http" and "hash" mode.
    domain_source = [ 
        "https://antifilter.download/list/domains.lst"
    ] # Deduplicate and Merge into new.txt
    ip_source = [
        "https://antifilter.download/list/ipresolve.lst",
        "https://antifilter.download/list/subnet.lst" 
    ] # Unpack all addresses with prefixes, deduplicate and merge into newip.txt
    community_domain_sources = [
        "https://community.antifilter.download/list/domains.lst",
        "https://raw.githubusercontent.com/1andrevich/Re-filter-lists/main/community.lst"
    ] # Deduplicate and Merge into community.txt

[[extension]]
name = "Discord Sender"
desc = "Send new changes as embeds using your Discord-Bot"
source = "https://github.com/SHULKERPLAY/Zapretyan-Go"
path = "./extensions/discord-sender"
enabled = true
BOT_TOKEN = ""
# Enable message types
isban = true     # Send Banned Domains
isunban = true   # Send Unbanned Domains
isbanip = true   # Send Banned IP's
isunbanip = true # Send Banned IP's
istotal = true   # Send total statistics (dailystat extension with "latestjson = true" required)
#Chat id's to send lists
bancid = ""     # ChannelID: Today Banned Domains
unbancid = ""   # ChannelID: Today Unbanned Domains
banipcid = ""   # ChannelID: Today Banned IP's
unbanipcid = "" # ChannelID: Today Unbanned IP's
totalcid = ""   # ChannelID: Daily and total Statistics (dailystat extension with "latestjson = true" required)
    [extension.override]
    iconurl = "https://lunarcreators.ru/wp-content/uploads/2025/11/discordiconmini.webp"
    embed_author_name = "Запретян <3"
    embed_author_url = "https://discord.com/discovery/applications/907372459144147035"
    # Embed colors (e.g HEX_COLOR)
    banclr = "ff5e5e"
    unbanclr = "5e87ff"
    banipclr = "ffa45e"
    unbanipclr = "5effac"
    totalclr = "ffff7d"
        [extension.override.locale]
        stats_date = "📌 Статистика за "
        stats_domains = "ДОМЕНЫ"
        stats_ips = "IP АДРЕСА"
        stats_past24h = "за прошедшие сутки"
        today_banned = "Сегодня заблокировано"
        today_unbanned = "Сегодня разблокировано"
        total_banned = "Всего заблокировано"
        domains_newbanned = "В список ограниченных ресурсов добавили:"
        domains_banned = "Заблокировано доменов"
        domains_newunbanned = "Из реестра удалены ресурсы:"
        domains_unbanned = "Разблокировано доменов"
        ip_newbanned = "В реестр добавили IP адреса:"
        ip_banned = "Заблокировано IP адресов"
        ip_newunbanned = "Из реестра удалены IP адреса:"
        ip_unbanned = "Разблокировано IP адресов"

[[extension]]
name = "File Logger"
desc = "Write every event JSON into ./data/localfs_dir"
source = "https://github.com/SHULKERPLAY/Zapretyan-Go"
path = "./extensions/localfs"
enabled = false
save_last_entries = 100        # Amount of latest files to be saved
localfs_dir = "localfs_logger" # Directory inside data folder

[[extension]]
name = "Daily Statistics"
desc = "Write daily statistics to today's JSON and historical CSV in Data folder"
source = "https://github.com/SHULKERPLAY/Zapretyan-Go"
path = "./extensions/dailystat"
enabled = false
latestjson = true      # Enable JSON with last day data about ban counters 
analytics = true       # Enable bans data collecting in analytics.csv
day_start = "00:00:00" # Local time write daily stats and reset daily counters