[core]
allow_custom_extensions = false
report_interval = 1           # In Hours (Up to 720 (30d))
send_empty_report = true      # Start events even if all fields are (empty: true)
once_ctx_deadline = 3300      # Kill extension process with "mode: "ONCE"" after this amount of seconds. Must NOT be more than (report_interval * 3600)
disable_ip_comparsion = false # Whether to disable scanning banned IP diffs
disable_community = true      # Whether to disable downloading of []community_domain_sources
    [core.data]
    data_dir = "./data" # Directory with necessary service files
    method = "http"     # If "http" then core checks for Last-Modified tag to check if file was updated and downloading files only if remote server has newer file.
                        # If "hash" then core downloading all files every scan. Hash compare of merged files performed in both "http" and "hash" mode.
    domain_source = [ 
        "https://antifilter.download/list/domains.lst"
    ] # Deduplicate and Merge into new.txt
    ip_source = [
        "https://antifilter.download/list/ipresolve.lst",
        "https://antifilter.download/list/subnet.lst" 
    ] # Unpack all addresses with prefixes, deduplicate and merge into newip.txt
    community_domain_sources = [
        "https://community.antifilter.download/list/domains.lst",
        "https://raw.githubusercontent.com/1andrevich/Re-filter-lists/main/community.lst"
    ] # Deduplicate and Merge into community.txt

[[extension]]
name = "Discord Sender"
desc = "Send new changes as embeds using your Discord-Bot"
source = "https://github.com/SHULKERPLAY/Zapretyan-Go"
path = "./extensions/discord-sender"
enabled = false
BOT_TOKEN = ""

[extension.sender] # Enable message types
isban = true     # Send Banned Domains
isunban = true   # Send Unbanned Domains
isbanip = true   # Send Banned IP's (mmdb country and asn databases required)
isunbanip = true # Send Banned IP's (mmdb country and asn databases required)
istotal = true   # Send total statistics ("Daily Statistics" extension with "latestjson = true" required)

[extension.data] # Data sources for send
mmdb_update = true                             # Check updates and update databases if file >45 days old (updates from db-ip.com)
mmdb_lang = "ru"                               # Supported langs with db-ip: "de", "en", "es", "fa", "fr", "ja", "ko", "pt-BR", "ru", "zh-CN"
mmdbasn_path = "./dissender/dbip-asn.mmdb"     # Path to mmdb ASN database
mmdbcountry_path = "./dissender/dbip-asn.mmdb" # Path to mmdb Country database
total_json_path = "./statistics/latest.json"   # Path to "Daily Statistics" JSON file

[extension.channels] #Chat id's to send lists
bancid = ""     # ChannelID: Today Banned Domains
unbancid = ""   # ChannelID: Today Unbanned Domains
banipcid = ""   # ChannelID: Today Banned IP's (mmdb country and asn databases required)
unbanipcid = "" # ChannelID: Today Unbanned IP's (mmdb country and asn databases required)
totalcid = ""   # ChannelID: Daily and total Statistics (dailystat extension with "latestjson = true" required)

[extension.embed] # Override internal embed states
iconurl = "https://lunarcreators.ru/wp-content/uploads/2025/11/discordiconmini.webp"
embed_author_name = "Запретян-Go <3"
embed_author_url = "https://discord.com/discovery/applications/907372459144147035"
# Embed colors (HEX e.g. 0fafff)
banclr = "ff5e5e"
unbanclr = "5e87ff"
banipclr = "ffa45e"
unbanipclr = "5effac"
totalclr = "ffff7d"

[extension.locale] # Override output messages text
stats_date = "Статистика за" # ...26/06/2026
domains = "Домены"
ips = "IP Адреса"
today_banned = "Сегодня заблокировано"
today_unbanned = "Сегодня разблокировано"
total_banned = "Всего заблокировано"
newbanned = "В реестр Роскомнадзора добавлены"
banned = "Добавлено записей"
newunbanned = "Из реестра Роскомнадзора удалены"
unbanned = "Удалено записей"
top_country = "Топ стран"
top_isp = "Топ провайдеров"

[[extension]]
name = "File Logger"
desc = "Write every event JSON into ./data/localfs_dir"
source = "https://github.com/SHULKERPLAY/Zapretyan-Go"
path = "./extensions/localfs"
enabled = false
save_last_entries = 100        # Amount of latest files to be saved
localfs_dir = "localfs_logger" # Directory inside data folder

[[extension]]
name = "Daily Statistics"
desc = "Write daily statistics to today's JSON and historical CSV"
source = "https://github.com/SHULKERPLAY/Zapretyan-Go"
path = "./extensions/dailystat"
enabled = false
latestjson = false                        # Enable JSON with last day data about ban counters
json_file = "./statistics/latest.json"    # Path to JSON relative to core data folder
analytics = true                          # Enable bans data collecting in analytics.csv
csv_file = "./statistics/analyticsV2.csv" # Path to CSV relative to core data folder
day_start = 0                             # Hour after which daily stats will be written daily counters reset to zero (0 to 23)
    [extension.locale]
    for24hrs = "за 24 часа"